### ISSUE TITLE
provide commonjs builds

### ISSUE THREAD

**Issue by stewones** [gamemaker1/office-text-extractor#11]
### Description

provide commonjs builds

### Why

not everyone is running es modules

### Alternatives

N/A

**Comment by gamemaker1** [comment]
Hi,

I don't think I'll be able to do that because a dependency of this package, `file-type`, is pure esm since [v17.0.0](https://github.com/sindresorhus/file-type/releases/tag/v17.0.0) and it made support for pdf detection better in [v18.2.1](https://github.com/sindresorhus/file-type/releases/tag/v18.2.1).

If you wish to use the package in a commonjs program, you could use version 1.5.0, which is the last cjs version of `office-text-extractor`.

Regards
